### PR TITLE
Add fast-fail, use gh CLI

### LINKED ISSUE #2: Add errors and fast fails

### LINKED ISSUE #3: Automate creating GitHub repo

### PR DESCRIPTION
**Pull request by tekktrik**
Adds more to the pre-gen hook to check for commands and fast-fail if they aren't available/installed.

Also adds the ability to create the Adafruit repository using the `gh` CLI.

Fixes #2
Fixes #3

### CODE REVIEW

**Comment by tekktrik** [comment]
Marking as draft until tested.

**Comment by kattni** [comment]
@tekktrik This is great! It certainly fails fast when things are not set up properly. Tested it successfully. 

I had to create a very particular fine-grained personal access token to make this happen - we will need to document the process in the README, preferably in this PR. I can update the README and push to the PR if it will let me.

Further, I would greatly appreciate it if you could make cookiecutter generate a `.gitignore` containing `.DS_Store`. I'm ok with that being a separate PR, though.

**Comment by tekktrik** [comment]
I can add the gitignore addition after this!

**Comment by kattni** [comment]
Oh! I realised a thing that is missing. When we create the new PCB repository on GitHub, we always add a repo description in the creation process. Please add this into the creation process within cookiecutter as well. The text is as follows:
```
PCB files for {full-board-name-with-description}.
```

**Comment by tekktrik** [comment]
Should be ready for review!

**Pull request closed without merging**
